FROM golang:latest

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
RUN go mod tidy

COPY . ./

WORKDIR /app
RUN swag init -g cmd/main.go -o cmd/docs

WORKDIR /app/cmd
RUN go mod tidy && go build -gcflags "all=-N -l" -o /app/myapp .

EXPOSE 8080 40000

CMD ["dlv", "exec", "/app/myapp", "--headless", "--listen=:40000", "--api-version=2", "--accept-multiclient"]
