<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRhkMLAF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRhkMLAF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRhkMLAF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRhkMLAF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRhkMLAF\App_KernelDevDebugContainer([
    'container.build_hash' => 'RhkMLAF',
    'container.build_id' => '8b1e0bb5',
    'container.build_time' => 1758121061,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRhkMLAF');
